name: Flamegraph
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  flamegraph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-flamegraph
        run: cargo install flamegraph --locked
      - name: Install perf
        run: |
          sudo apt-get update
          sudo apt-get install -y linux-tools-common "linux-tools-$(uname -r)" || \
            sudo apt-get install -y linux-tools-generic
          sudo bash -c 'echo 0 > /proc/sys/kernel/perf_event_paranoid'
      - name: Generate flamegraph
        run: cargo flamegraph --package flameview --bench add_one -- --bench
      - name: Collect line-level perf information
        run: |
          set -euxo pipefail
          RUSTFLAGS="-C force-frame-pointers=yes" \
            cargo bench --bench add_one --no-run
          BIN=$(find target/release/deps -maxdepth 1 -executable -name 'add_one-*' | head -n 1)
          echo "Benchmark binary: $BIN"
          PERF_BIN=$(find /usr/lib/linux-tools* -maxdepth 2 -name perf | sort -V | tail -n 1)
          if [ -z "$PERF_BIN" ]; then
            PERF_BIN=$(command -v perf)
          fi
          echo "Using perf from $PERF_BIN"
          sudo "$PERF_BIN" record -F 200 --call-graph fp -o perf.data -- \
            "$BIN" --bench add_one --sample-size 10 --measurement-time 1
          sudo chown "$(id -u):$(id -g)" perf.data
          "$PERF_BIN" report -i perf.data -g fractal -F+srcline --stdio > perf_report.txt
          python3 scripts/perf_snippet.py perf_report.txt | tee perf_with_code.txt
      - name: Upload flamegraph
        uses: actions/upload-artifact@v4
        with:
          name: flameview-flamegraph
          path: |
            flamegraph.svg
            perf_report.txt
            perf_with_code.txt
